language: generic
sudo: false
env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="source"
    - DEPLOY_BRANCH="master"
    - GIT_NAME="David Shorter"
    - GIT_EMAIL="shorter.david@gmail.com"
    - ENCRYPTION_LABEL="e9ba5a00b9e2"

install:
    - chmod a+x "./build/install-hugo.sh"
    - ./build/install-hugo.sh

script:
    - ./hugo version
    - ./hugo -v

after_success:
    - chmod a+x "./build/publish.sh"
    - "./build/publish.sh"